package co.afrolabs.truevote.constant;

public enum StateEnum {
	ABIA,ADAMAWA,AKWA_IBOM,ANAMBRA,BAUCHI, BAYELSA, BENUE, BORNU, CROSS_RIVER,
	DELTA,EBONYI,EDO, EKITI,ENUGU, FCT, GOMBE, IMO, JIGAWA, KADUNA, KANO,
	KATSINA, KEBBI, KOGI, KWARA, LAGOS, NASARAWA, NIGER, OGUN, ONDO,OSUN,
	OYO, PLATEAU, RIVERS, SOKOTO, TARABA, YOBE, ZAMFARA
}
